import { MouseEventHandler } from "react";
import OotIcon, { IconData, IconDict } from "./OotIcon";

export interface OotItemIconProps {
    itemName: string,
    price?: number | null,
    sourceLocation?: string | null,
    className?: string,
    onClick?: MouseEventHandler,
}

type KeyTextDict = {
    [key: string]: string;
}

const keyMap: KeyTextDict = {
    'Deku Tree': 'DT',
    'Dodongos Cavern': 'DC',
    'Jabu Jabus Belly': 'JJ',
    'Forest Temple': 'Fo',
    'Fire Temple': 'Fi',
    'Water Temple': 'Wa',
    'Spirit Temple': 'Sp',
    'Shadow Temple': 'Sh',
    'Ganons Castle': 'GC',
    'Bottom of the Well': 'We',
    'Ice Cavern': 'Ice',
    'Gerudo Training Ground': 'GTG',
    'Thieves Hideout': 'Hi',
    'Treasure Chest Game': 'TCG',
    '???': '?'
};

const itemMap: IconDict = {
    'Deku Stick Capacity': { img: '/images/OoT_Deku_Stick_Icon.png' },
    'Deku Nut Capacity': { img: '/images/OoT_Deku_Nut_Icon.png' },
    'Bomb Bag': { img: '/images/OoT_Bomb_Bag_Icon.png' },
    'Bow': { img: '/images/OoT_Fairy_Bow_Icon.png' },
    'Fire Arrows': { img: '/images/OoT_Fire_Arrow_Icon.png' },
    'Dins Fire': { img: '/images/OoT_Dins_Fire_Icon.png' },
    'Kokiri Sword': { img: '/images/OoT_Kokiri_Sword_Icon.png' },
    'Master Sword': { img: '/images/OoT_Master_Sword_Icon.png' },
    'Giants Knife': { img: '/images/OoT_Giants_Knife_Icon.png' },
    'Biggoron Sword': { img: '/images/OoT_Giants_Knife_Icon.png' },
    'Slingshot': { img: '/images/OoT_Fairy_Slingshot_Icon.png' },
    'Ocarina': { img: '/images/OoT_Fairy_Ocarina_Icon.png' },
    'Bombchus': { img: '/images/OoT_Bombchu_Icon.png' },
    'Bombchus (5)': { img: '/images/OoT_Bombchu_Icon.png' },
    'Bombchus (10)': { img: '/images/OoT_Bombchu_Icon.png' },
    'Bombchus (20)': { img: '/images/OoT_Bombchu_Icon.png' },
    'Progressive Hookshot': { img: '/images/OoT_Hookshot_Icon.png' },
    'Ice Arrows': { img: '/images/OoT_Ice_Arrow_Icon.png' },
    'Blue Fire Arrows': { img: '/images/OoT_Ice_Arrow_Icon.png' },
    'Farores Wind': { img: '/images/OoT_Farores_Wind_Icon.png' },
    'Deku Shield': { img: '/images/OoT_Deku_Shield_Icon.png' },
    'Hylian Shield': { img: '/images/OoT_Hylian_Shield_Icon.png' },
    'Mirror Shield': { img: '/images/OoT_Mirror_Shield_Icon.png' },
    'Boomerang': { img: '/images/OoT_Boomerang_Icon.png' },
    'Lens of Truth': { img: '/images/OoT_Lens_of_Truth_Icon.png' },
    'Magic Bean Pack': { img: '/images/OoT_Magic_Bean_Icon.png', rSub: '10' },
    'Magic Bean': { img: '/images/OoT_Magic_Bean_Icon.png' },
    'Buy Magic Bean': { img: '/images/OoT_Magic_Bean_Icon.png' },
    'Megaton Hammer': { img: '/images/OoT_Megaton_Hammer_Icon.png' },
    'Light Arrows': { img: '/images/OoT_Light_Arrow_Icon.png' },
    'Nayrus Love': { img: '/images/OoT_Nayrus_Love_Icon.png' },
    'Progressive Strength Upgrade': { img: '/images/OoT_Gorons_Bracelet_Icon.png' },
    'Goron Tunic': { img: '/images/OoT_Goron_Tunic_Icon.png' },
    'Zora Tunic': { img: '/images/OoT_Zora_Tunic_Icon.png' },
    'Bottle': { img: '/images/OoT_Bottle_Icon.png' },
    'Adult Trade Item': { img: '/images/OoT_Cojiro_Icon.png' },
    'Child Trade Item': { img: '/images/OoT_Cucco_Icon.png' },
    'Progressive Scale': { img: '/images/OoT_Silver_Scale_Icon.png' },
    'Iron Boots': { img: '/images/OoT_Iron_Boots_Icon.png' },
    'Hover Boots': { img: '/images/OoT_Hover_Boots_Icon.png' },
    'Zeldas Lullaby': { img: '/images/Red_Note.png', rSub: 'Z' },
    'Eponas Song': { img: '/images/Orange_Note.png', rSub: 'E' },
    'Sarias Song': { img: '/images/Green_Note.png', rSub: 'S' },
    'Suns Song': { img: '/images/Yellow_Note.png', rSub: 'S' },
    'Song of Time': { img: '/images/Blue_Note.png', rSub: 'T' },
    'Song of Storms': { img: '/images/Purple_Note.png', rSub: 'S' },
    'Progressive Wallet': { img: '/images/OoT_Adults_Wallet_Icon.png' },
    'Magic Meter': { img: '/images/OoT_Small_Magic_Jar_Icon.png' },
    'Gold Skulltula Token': { img: '/images/OoT_Token_Icon.png' },
    'Minuet of Forest': { img: '/images/Green_Note.png', rSub: 'M' },
    'Bolero of Fire': { img: '/images/Red_Note.png', rSub: 'B' },
    'Serenade of Water': { img: '/images/Blue_Note.png', rSub: 'W' },
    'Requiem of Spirit': { img: '/images/Orange_Note.png', rSub: 'R' },
    'Nocturne of Shadow': { img: '/images/Purple_Note.png', rSub: 'N' },
    'Prelude of Light': { img: '/images/Yellow_Note.png', rSub: 'P' },
    'Gerudo Membership Card': { img: '/images/OoT_Gerudo_Token_Icon.png' },
    'Stone of Agony': { img: '/images/OoT_Stone_of_Agony_Icon.png' },
    'Triforce Piece': { img: '/images/OoT_Triforce.png' },
    'Rutos Letter': { img: '/images/OoT_Letter_Icon.png' },
    'Bottle with Big Poe': { img: '/images/OoT_Big_Poe_Soul_Icon.png' },
    'Map (Deku Tree)': { img: '/images/OoT_Dungeon_Map_Icon.png', rSub: keyMap['Deku Tree'] },
    'Map (Dodongos Cavern)': { img: '/images/OoT_Dungeon_Map_Icon.png', rSub: keyMap['Dodongos Cavern'] },
    'Map (Jabu Jabus Belly)': { img: '/images/OoT_Dungeon_Map_Icon.png', rSub: keyMap['Jabu Jabus Belly'] },
    'Map (Forest Temple)': { img: '/images/OoT_Dungeon_Map_Icon.png', rSub: keyMap['Forest Temple'] },
    'Map (Fire Temple)': { img: '/images/OoT_Dungeon_Map_Icon.png', rSub: keyMap['Fire Temple'] },
    'Map (Water Temple)': { img: '/images/OoT_Dungeon_Map_Icon.png', rSub: keyMap['Water Temple'] },
    'Map (Spirit Temple)': { img: '/images/OoT_Dungeon_Map_Icon.png', rSub: keyMap['Spirit Temple'] },
    'Map (Shadow Temple)': { img: '/images/OoT_Dungeon_Map_Icon.png', rSub: keyMap['Shadow Temple'] },
    'Map (Ganons Castle)': { img: '/images/OoT_Dungeon_Map_Icon.png', rSub: keyMap['Ganons Castle'] },
    'Map (Bottom of the Well)': { img: '/images/OoT_Dungeon_Map_Icon.png', rSub: keyMap['Bottom of the Well'] },
    'Map (Ice Cavern)': { img: '/images/OoT_Dungeon_Map_Icon.png', rSub: keyMap['Ice Cavern'] },
    'Compass (Deku Tree)': { img: '/images/OoT_Compass_Icon.png', rSub: keyMap['Deku Tree'] },
    'Compass (Dodongos Cavern)': { img: '/images/OoT_Compass_Icon.png', rSub: keyMap['Dodongos Cavern'] },
    'Compass (Jabu Jabus Belly)': { img: '/images/OoT_Compass_Icon.png', rSub: keyMap['Jabu Jabus Belly'] },
    'Compass (Forest Temple)': { img: '/images/OoT_Compass_Icon.png', rSub: keyMap['Forest Temple'] },
    'Compass (Fire Temple)': { img: '/images/OoT_Compass_Icon.png', rSub: keyMap['Fire Temple'] },
    'Compass (Water Temple)': { img: '/images/OoT_Compass_Icon.png', rSub: keyMap['Water Temple'] },
    'Compass (Spirit Temple)': { img: '/images/OoT_Compass_Icon.png', rSub: keyMap['Spirit Temple'] },
    'Compass (Shadow Temple)': { img: '/images/OoT_Compass_Icon.png', rSub: keyMap['Shadow Temple'] },
    'Compass (Ganons Castle)': { img: '/images/OoT_Compass_Icon.png', rSub: keyMap['Ganons Castle'] },
    'Compass (Bottom of the Well)': { img: '/images/OoT_Compass_Icon.png', rSub: keyMap['Bottom of the Well'] },
    'Compass (Ice Cavern)': { img: '/images/OoT_Compass_Icon.png', rSub: keyMap['Ice Cavern'] },
    'Small Key (Forest Temple)': { img: '/images/OoT_Small_Key_Icon.png', rSub: keyMap['Forest Temple'] },
    'Small Key (Fire Temple)': { img: '/images/OoT_Small_Key_Icon.png', rSub: keyMap['Fire Temple'] },
    'Small Key (Water Temple)': { img: '/images/OoT_Small_Key_Icon.png', rSub: keyMap['Water Temple'] },
    'Small Key (Spirit Temple)': { img: '/images/OoT_Small_Key_Icon.png', rSub: keyMap['Spirit Temple'] },
    'Small Key (Shadow Temple)': { img: '/images/OoT_Small_Key_Icon.png', rSub: keyMap['Shadow Temple'] },
    'Small Key (Ganons Castle)': { img: '/images/OoT_Small_Key_Icon.png', rSub: keyMap['Ganons Castle'] },
    'Small Key (Bottom of the Well)': { img: '/images/OoT_Small_Key_Icon.png', rSub: keyMap['Bottom of the Well'] },
    'Small Key (Gerudo Training Ground)': { img: '/images/OoT_Small_Key_Icon.png', rSub: keyMap['Gerudo Training Ground'] },
    'Small Key (Thieves Hideout)': { img: '/images/OoT_Small_Key_Icon.png', rSub: keyMap['Thieves Hideout'] },
    'Small Key (Treasure Chest Game)': { img: '/images/OoT_Small_Key_Icon.png', rSub: keyMap['Treasure Chest Game'] },
    'Small Key (???)': { img: '/images/OoT_Small_Key_Icon.png', rSub: keyMap['???'] },
    'Small Key Ring (Forest Temple)': { img: '/images/OoT_keyring_Icon.png', rSub: keyMap['Forest Temple'] },
    'Small Key Ring (Fire Temple)': { img: '/images/OoT_keyring_Icon.png', rSub: keyMap['Fire Temple'] },
    'Small Key Ring (Water Temple)': { img: '/images/OoT_keyring_Icon.png', rSub: keyMap['Water Temple'] },
    'Small Key Ring (Spirit Temple)': { img: '/images/OoT_keyring_Icon.png', rSub: keyMap['Spirit Temple'] },
    'Small Key Ring (Shadow Temple)': { img: '/images/OoT_keyring_Icon.png', rSub: keyMap['Shadow Temple'] },
    'Small Key Ring (Ganons Castle)': { img: '/images/OoT_keyring_Icon.png', rSub: keyMap['Ganons Castle'] },
    'Small Key Ring (Bottom of the Well)': { img: '/images/OoT_keyring_Icon.png', rSub: keyMap['Bottom of the Well'] },
    'Small Key Ring (Gerudo Training Ground)': { img: '/images/OoT_keyring_Icon.png', rSub: keyMap['Gerudo Training Ground'] },
    'Small Key Ring (Thieves Hideout)': { img: '/images/OoT_keyring_Icon.png', rSub: keyMap['Thieves Hideout'] },
    'Small Key Ring (Treasure Chest Game)': { img: '/images/OoT_keyring_Icon.png', rSub: keyMap['Treasure Chest Game'] },
    'Small Key Ring (???)': { img: '/images/OoT_keyring_Icon.png', rSub: keyMap['???'] },
    'Boss Key (Forest Temple)': { img: '/images/OoT_Boss_Key_Icon.png', rSub: keyMap['Forest Temple'] },
    'Boss Key (Fire Temple)': { img: '/images/OoT_Boss_Key_Icon.png', rSub: keyMap['Fire Temple'] },
    'Boss Key (Water Temple)': { img: '/images/OoT_Boss_Key_Icon.png', rSub: keyMap['Water Temple'] },
    'Boss Key (Spirit Temple)': { img: '/images/OoT_Boss_Key_Icon.png', rSub: keyMap['Spirit Temple'] },
    'Boss Key (Shadow Temple)': { img: '/images/OoT_Boss_Key_Icon.png', rSub: keyMap['Shadow Temple'] },
    'Boss Key (Ganons Castle)': { img: '/images/OoT_Boss_Key_Icon.png', rSub: keyMap['Ganons Castle'] },
    'Boss Key (???)': { img: '/images/OoT_Boss_Key_Icon.png', rSub: keyMap['???'] },
    'Green Rupee': { img: '/images/Green_Rupee.png' },
    'Blue Rupee': { img: '/images/Blue_Rupee.png' },
    'Red Rupee': { img: '/images/Red_Rupee.png' },
    'Purple Rupee': { img: '/images/Purple_Rupee.png' },
    'Arrows': { img: '/images/OoT_Arrows_Icon.png' },
    'Deku Seeds': { img: '/images/OoT_Deku_Seeds_Icon.png' },
    'Bombs': { img: '/images/OoT_Bomb_Icon.png' },
    'Deku Stick': { img: '/images/OoT_Deku_Stick_Icon.png' },
    'Blue Fire': { img: '/images/OoT_Blue_Fire_Icon.png' },
    'Piece of Heart': { img: '/images/OoT_Piece_of_Heart_Icon.png' },
    'Piece of Heart (Treasure Chest Game)': { img: '/images/OoT_Piece_of_Heart_Icon.png' },
    'Heart Container': { img: '/images/OoT_Heart_Container_Icon.png' },
    'Weird Egg': { img: '/images/OoT_Weird_Egg_Icon.png', rSub: 'C' },
    'Chicken': { img: '/images/OoT_Cucco_Icon.png', rSub: 'C' },
    'Zeldas Letter': { img: '/images/OoT_Zeldas_Letter_Icon.png' },
    'Keaton Mask': { img: '/images/OoT_Keaton_Mask_Icon.png' },
    'Skull Mask': { img: '/images/OoT_Skull_Mask_Icon.png' },
    'Spooky Mask': { img: '/images/OoT_Spooky_Mask_Icon.png' },
    'Bunny Hood': { img: '/images/OoT_Bunny_Hood_Icon.png' },
    'Mask of Truth': { img: '/images/OoT_Mask_of_Truth_Icon.png' },
    'Pocket Egg': { img: '/images/OoT_Weird_Egg_Icon.png', rSub: 'A' },
    'Pocket Cucco': { img: '/images/OoT_Cucco_Icon.png', rSub: 'A' },
    'Cojiro': { img: '/images/OoT_Cojiro_Icon.png' },
    'Odd Mushroom': { img: '/images/OoT_Odd_Mushroom_Icon.png' },
    'Odd Potion': { img: '/images/OoT_Odd_Potion_Icon.png' },
    'Poachers Saw': { img: '/images/OoT_Poachers_Saw_Icon.png' },
    'Broken Sword': { img: '/images/OoT_Broken_Gorons_Sword_Icon.png' },
    'Prescription': { img: '/images/OoT_Prescription_Icon.png' },
    'Eyeball Frog': { img: '/images/OoT_Eyeball_Frog_Icon.png' },
    'Eyedrops': { img: '/images/OoT_Worlds_Finest_Eye_Drops_Icon.png' },
    'Claim Check': { img: '/images/OoT_Claim_Check_Icon.png' },
    'Kokiri Emerald': { img: '/images/OoT_Spiritual_Stone_of_the_Forest_Icon.png' },
    'Goron Ruby': { img: '/images/OoT_Spiritual_Stone_of_Fire_Icon.png' },
    'Zora Sapphire': { img: '/images/OoT_Spiritual_Stone_of_Water_Icon.png' },
    'Forest Medallion': { img: '/images/OoT_Forest_Medallion_Icon.png' },
    'Fire Medallion': { img: '/images/OoT_Fire_Medallion_Icon.png' },
    'Water Medallion': { img: '/images/OoT_Water_Medallion_Icon.png' },
    'Spirit Medallion': { img: '/images/OoT_Spirit_Medallion_Icon.png' },
    'Shadow Medallion': { img: '/images/OoT_Shadow_Medallion_Icon.png' },
    'Light Medallion': { img: '/images/OoT_Light_Medallion_Icon.png' },
    'Silver Rupee (Dodongos Cavern Staircase)': { img: '/images/Silver_Rupee.png', rSub: 'DC' },
    'Silver Rupee (Ice Cavern Spinning Scythe)': { img: '/images/Silver_Rupee.png', rSub: 'Ice' },
    'Silver Rupee (Ice Cavern Push Block)': { img: '/images/Silver_Rupee.png', rSub: 'Ice' },
    'Silver Rupee (Bottom of the Well Basement)': { img: '/images/Silver_Rupee.png', rSub: 'We' },
    'Silver Rupee (Shadow Temple Scythe Shortcut)': { img: '/images/Silver_Rupee.png', rSub: 'Sh' },
    'Silver Rupee (Shadow Temple Invisible Blades)': { img: '/images/Silver_Rupee.png', rSub: 'Sh' },
    'Silver Rupee (Shadow Temple Huge Pit)': { img: '/images/Silver_Rupee.png', rSub: 'Sh' },
    'Silver Rupee (Shadow Temple Invisible Spikes)': { img: '/images/Silver_Rupee.png', rSub: 'Sh' },
    'Silver Rupee (Gerudo Training Ground Slopes)': { img: '/images/Silver_Rupee.png', rSub: 'GTG' },
    'Silver Rupee (Gerudo Training Ground Lava)': { img: '/images/Silver_Rupee.png', rSub: 'GTG' },
    'Silver Rupee (Gerudo Training Ground Water)': { img: '/images/Silver_Rupee.png', rSub: 'GTG' },
    'Silver Rupee (Spirit Temple Child Early Torches)': { img: '/images/Silver_Rupee.png', rSub: 'Sp' },
    'Silver Rupee (Spirit Temple Adult Boulders)': { img: '/images/Silver_Rupee.png', rSub: 'Sp' },
    'Silver Rupee (Spirit Temple Lobby and Lower Adult)': { img: '/images/Silver_Rupee.png', rSub: 'Sp' },
    'Silver Rupee (Spirit Temple Sun Block)': { img: '/images/Silver_Rupee.png', rSub: 'Sp' },
    'Silver Rupee (Spirit Temple Adult Climb)': { img: '/images/Silver_Rupee.png', rSub: 'Sp' },
    'Silver Rupee (Ganons Castle Spirit Trial)': { img: '/images/Silver_Rupee.png', rSub: 'SpT' },
    'Silver Rupee (Ganons Castle Light Trial)': { img: '/images/Silver_Rupee.png', rSub: 'LiT' },
    'Silver Rupee (Ganons Castle Fire Trial)': { img: '/images/Silver_Rupee.png', rSub: 'FiT' },
    'Silver Rupee (Ganons Castle Shadow Trial)': { img: '/images/Silver_Rupee.png', rSub: 'ShT' },
    'Silver Rupee (Ganons Castle Water Trial)': { img: '/images/Silver_Rupee.png', rSub: 'WaT' },
    'Silver Rupee (Ganons Castle Forest Trial)': { img: '/images/Silver_Rupee.png', rSub: 'FoT' },
    'Silver Rupee (???)': { img: '/images/Silver_Rupee.png', rSub: '?' },
    'Silver Rupee Pouch (Dodongos Cavern Staircase)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'DC' },
    'Silver Rupee Pouch (Ice Cavern Spinning Scythe)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'Ice' },
    'Silver Rupee Pouch (Ice Cavern Push Block)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'Ice' },
    'Silver Rupee Pouch (Bottom of the Well Basement)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'We' },
    'Silver Rupee Pouch (Shadow Temple Scythe Shortcut)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'Sh' },
    'Silver Rupee Pouch (Shadow Temple Invisible Blades)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'Sh' },
    'Silver Rupee Pouch (Shadow Temple Huge Pit)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'Sh' },
    'Silver Rupee Pouch (Shadow Temple Invisible Spikes)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'Sh' },
    'Silver Rupee Pouch (Gerudo Training Ground Slopes)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'GTG' },
    'Silver Rupee Pouch (Gerudo Training Ground Lava)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'GTG' },
    'Silver Rupee Pouch (Gerudo Training Ground Water)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'GTG' },
    'Silver Rupee Pouch (Spirit Temple Child Early Torches)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'Sp' },
    'Silver Rupee Pouch (Spirit Temple Adult Boulders)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'Sp' },
    'Silver Rupee Pouch (Spirit Temple Lobby and Lower Adult)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'Sp' },
    'Silver Rupee Pouch (Spirit Temple Sun Block)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'Sp' },
    'Silver Rupee Pouch (Spirit Temple Adult Climb)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'Sp' },
    'Silver Rupee Pouch (Ganons Castle Spirit Trial)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'SpT' },
    'Silver Rupee Pouch (Ganons Castle Light Trial)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'LiT' },
    'Silver Rupee Pouch (Ganons Castle Fire Trial)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'FiT' },
    'Silver Rupee Pouch (Ganons Castle Shadow Trial)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'ShT' },
    'Silver Rupee Pouch (Ganons Castle Water Trial)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'WaT' },
    'Silver Rupee Pouch (Ganons Castle Forest Trial)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: 'FoT' },
    'Silver Rupee Pouch (???)': { img: '/images/OoT_Adults_Wallet_Icon.png', rSub: '?' },
    'Ocarina A Button': { img: '/images/ocarina_a.blue.png' },
    'Ocarina C up Button': { img: '/images/ocarina_c_up.yellow.png' },
    'Ocarina C down Button': { img: '/images/ocarina_c_down.yellow.png' },
    'Ocarina C right Button': { img: '/images/ocarina_c_right.yellow.png' },
    'Ocarina C left Button': { img: '/images/ocarina_c_left.yellow.png' },
    'Song': { img: '/images/Grey_Note.png' },
    'Buy Deku Nut (5)': { img: '/images/OoT_Deku_Nut_Icon.png' },
    'Buy Arrows (30)': { img: '/images/OoT_Arrows_Icon.png' },
    'Buy Arrows (50)': { img: '/images/OoT_Arrows_Icon.png' },
    'Buy Bombs (5) for 25 Rupees': { img: '/images/OoT_Bomb_Icon.png' },
    'Buy Deku Nut (10)': { img: '/images/OoT_Deku_Nut_Icon.png' },
    'Buy Deku Stick (1)': { img: '/images/OoT_Deku_Stick_Icon.png' },
    'Buy Bombs (10)': { img: '/images/OoT_Bomb_Icon.png' },
    'Buy Fish': { img: '/images/OoT_Fish_Icon.png' },
    'Buy Red Potion for 30 Rupees': { img: '/images/OoT_Red_Potion_Icon.png' },
    'Buy Green Potion': { img: '/images/OoT_Green_Potion_Icon.png' },
    'Buy Blue Potion': { img: '/images/OoT_Blue_Potion_Icon.png' },
    'Buy Hylian Shield': { img: '/images/OoT_Hylian_Shield_Icon.png' },
    'Buy Deku Shield': { img: '/images/OoT_Deku_Shield_Icon.png' },
    'Buy Goron Tunic': { img: '/images/OoT_Goron_Tunic_Icon.png' },
    'Buy Zora Tunic': { img: '/images/OoT_Zora_Tunic_Icon.png' },
    'Buy Bombchu (10)': { img: '/images/OoT_Bombchu_Icon.png' },
    'Buy Bombchu (20)': { img: '/images/OoT_Bombchu_Icon.png' },
    'Buy Bombchu (5)': { img: '/images/OoT_Bombchu_Icon.png' },
    'Buy Deku Seeds (30)': { img: '/images/OoT_Deku_Seeds_Icon.png' },
    'Buy Blue Fire': { img: '/images/OoT_Blue_Fire_Icon.png' },
    'Buy Bottle Bug': { img: '/images/OoT_Bug_Icon.png' },
    'Buy Poe': { img: '/images/OoT_Poe_Soul_Icon.png' },
    'Buy Fairy\'s Spirit': { img: '/images/OoT_Fairy_Icon.png' },
    'Buy Arrows (10)': { img: '/images/OoT_Arrows_Icon.png' },
    'Buy Bombs (20)': { img: '/images/OoT_Bomb_Icon.png' },
    'Buy Bombs (30)': { img: '/images/OoT_Bomb_Icon.png' },
    'Buy Bombs (5) for 35 Rupees': { img: '/images/OoT_Bomb_Icon.png' },
    'Buy Red Potion for 40 Rupees': { img: '/images/OoT_Red_Potion_Icon.png' },
    'Buy Red Potion for 50 Rupees': { img: '/images/OoT_Red_Potion_Icon.png' },
    'Buy Heart': { img: '/images/OoT_Heart_Icon.png' },
    'Rupees (200)': { img: '/images/Yellow_Rupee.png' },
    'Rupee (1)': { img: '/images/Green_Rupee.png' },
    'Rupees (5)': { img: '/images/Blue_Rupee.png' },
    'Rupees (20)': { img: '/images/Red_Rupee.png' },
    'Rupees (50)': { img: '/images/Purple_Rupee.png' },
    'Rupee (Treasure Chest Game) (1)': { img: '/images/Green_Rupee.png' },
    'Rupees (Treasure Chest Game) (5)': { img: '/images/Blue_Rupee.png' },
    'Rupees (Treasure Chest Game) (20)': { img: '/images/Red_Rupee.png' },
    'Rupees (Treasure Chest Game) (50)': { img: '/images/Purple_Rupee.png' },
    'Arrows (5)': { img: '/images/OoT_Arrows_Icon.png' },
    'Arrows (10)': { img: '/images/OoT_Arrows_Icon.png' },
    'Arrows (30)': { img: '/images/OoT_Arrows_Icon.png' },
    'Deku Seeds (30)': { img: '/images/OoT_Deku_Seeds_Icon.png' },
    'Bombs (1)': { img: '/images/OoT_Bomb_Icon.png' },
    'Bombs (5)': { img: '/images/OoT_Bomb_Icon.png' },
    'Bombs (10)': { img: '/images/OoT_Bomb_Icon.png' },
    'Bombs (20)': { img: '/images/OoT_Bomb_Icon.png' },
    'Deku Stick (1)': { img: '/images/OoT_Deku_Stick_Icon.png' },
    'Deku Nuts (5)': { img: '/images/OoT_Deku_Nut_Icon.png' },
    'Deku Nuts (10)': { img: '/images/OoT_Deku_Nut_Icon.png' },
    'Red Potion': { img: '/images/OoT_Red_Potion_Icon.png' },
    'Green Potion': { img: '/images/OoT_Green_Potion_Icon.png' },
    'Blue Potion': { img: '/images/OoT_Blue_Potion_Icon.png' },
    'Milk': { img: '/images/OoT_Milk_Icon.png' },
    'Bottle with Milk': { img: '/images/OoT_Milk_Icon.png' },
    'Bottle with Red Potion': { img: '/images/OoT_Red_Potion_Icon.png' },
    'Bottle with Green Potion': { img: '/images/OoT_Green_Potion_Icon.png' },
    'Bottle with Blue Potion': { img: '/images/OoT_Blue_Potion_Icon.png' },
    'Bottle with Fairy': { img: '/images/OoT_Fairy_Icon.png' },
    'Bottle with Fish': { img: '/images/OoT_Fish_Icon.png' },
    'Bottle with Blue Fire': { img: '/images/OoT_Blue_Fire_Icon.png' },
    'Bottle with Bugs': { img: '/images/OoT_Bug_Icon.png' },
    'Bottle with Poe': { img: '/images/OoT_Poe_Soul_Icon.png' },
    'Recovery Heart': { img: '/images/OoT_Heart_Icon.png' },
    'Ice Trap': { img: '/images/icetrap.png' },
    'Double Defense': { img: '/images/double_defense.png' },
};

export const haveOotItemIcon = (itemName: string) => {
    return Object.keys(itemMap).includes(itemName);
}

const OotItemIcon = ({
    itemName,
    price,
    sourceLocation,
    className,
    onClick,
}: OotItemIconProps) => {
    let imageData: IconData;
    if (!!price) {
        if (price < 100) {
            imageData = itemMap['Green Rupee'];
        } else if (price <= 200) {
            imageData = itemMap['Blue Rupee'];
        } else if (price <= 500) {
            imageData = itemMap['Red Rupee'];
        } else {
            imageData = itemMap['Purple Rupee'];
        }
    } else {
        imageData = itemMap[itemName];
    }
    if (!!imageData) {
        return (
            <OotIcon
                itemName={itemName}
                sourceLocation={sourceLocation}
                className={className}
                onClick={onClick}
                imageData={imageData}
            />
        );
    } else {
        return null;
    }
}

export default OotItemIcon;